### ISSUE TITLE
Make it nice

### ISSUE THREAD

**Issue by ElectricMaxxx** [developersforfuture/website#1]
The main purpose is development. But we also should mention and highihght these papers in our own website. To do so, the site needs a nice and easey redisn

**Comment by ElectricMaxxx** [comment]
This could be a nice layout:
![image](https://user-images.githubusercontent.com/2905834/55586609-ad0b8600-5729-11e9-902c-ac06df1fa199.png)

**Comment by ElectricMaxxx** [comment]
I currently work together with @crucion he provides me with really helpfull templates and css information: like:

![image](https://user-images.githubusercontent.com/2905834/55775969-758b3980-5a9b-11e9-801e-533106e40b19.png)

**Comment by ElectricMaxxx** [comment]
In parts this css is still included in parts:

```css
:root {
 font-family:Merriweather Sans, Lato, Cantarell, sans-serif;
 font-size:14px;
 
 --dark-green:#1B7340;
 --medium-green:#1DA64A;
 --light-green:#E1F2E7; /* #E0F6E8 */
 --white-green:#F4F9F6;
 --light-blue:#90D3ED;
 --gray:#565656;
 --light-gray:#EFEFEF;
 
 -moz-user-select:none;
 -webkit-user-select:none;
 -ms-user-select:none;
}

body {
 min-height:100vh;
 background-color:var(--light-gray);
 margin:0px;
}



p {
 margin:20px;
}

h1, h2, h3 {
 font-family:"Jost Semi", Lato, Cantarell, sans-serif;
 text-transform:uppercase;
}

h1 {
 font-size:26px;
 text-align:center;
 margin:40px 20px 20px 20px;
}

h2 {
 font-size:20px;
 text-align:center;
 margin:30px 20px 20px 20px;
}

h3 {
 font-size:18px;
 text-align:center;
 margin:30px 20px 20px 20px;
}

.button-container {
 width:100%;
 display:flex;
 flex-direction:row;
 align-items:center;
 justify-content:center;
}

button,
.button {
 height:40px;
 font-size:inherit;
 font-family:inherit;
 padding:0px 16px;
 color:#000000;
 background-color:var(--light-blue);
 border:0px;
 border-radius:5px;
 margin:10px;
 cursor:pointer;
 display:flex;
 flex-direction:row;
 align-items:center;
 justify-content:space-between;
 box-sizing:border-box;
}

button:hover,
.button:hover {
 color:#FFFFFF;
}

a {
 text-decoration:none;
 color:var(--medium-green);
}

a:hover {
 color:var(--light-blue);
}

img {
 max-width:calc(100% - 40px);
 border-radius:5px;
 margin:20px;
 display:flex;
}

iframe {
 width:100%;
 height:100%;
 border:0px;
}



.transparent {
 background-color:transparent !important;
}



header {
 width:100%;
 height:60px;
 font-size:16px;
 color:#FFFFFF;
 background-color:var(--medium-green);
 box-shadow:0px -15px 10px 10px black;
 z-index:6;
 display:flex;
 flex-direction:row;
 align-items:center;
 justify-content:space-between;
 box-sizing:border-box;
 position:sticky;
 top:0px;
}

#header-logo-space {
 color:#FFFFFF;
 padding:10px;
 display:flex;
 flex-direction:row;
 align-items:center;
 justify-content:center;
}

#header-logo {
 width:40px;
 height:40px;
 background-image:url(developers-for-future-logo.png);
 background-size:contain;
 background-position:center;
 background-repeat:no-repeat;
 border-radius:50%;
 cursor:pointer;
 display:flex;
}

#header-logo-title {
 margin-left:16px;
}

nav {
 height:100%;
 display:flex;
 flex-direction:row;
 align-items:center;
 justify-content:center;
}

nav ul {
 height:100%;
 padding:0px 6px 0px 0px;
 margin:0px;
 display:flex;
 flex-direction:row;
 align-items:center;
 justify-content:center;
 list-style:none;
}

nav ul li {
 height:100%;
 padding:0px;
 margin:0px;
 cursor:pointer;
}

nav ul li a {
 height:100%;
 color:#FFFFFF;
 padding:0px 16px 0px 16px;
 margin:0px;
 position:relative;
 display:flex;
 flex-direction:row;
 align-items:center;
 justify-content:center;
 box-sizing:border-box;
}

nav ul li a::after {
 content:"";
 width:calc(100% - 32px);
 height:0px;
 background-color:transparent;
 position:absolute;
 bottom:0px;
 border-radius:1px 1px 0px 0px;
 transition-property:height, background-color;
 transition-duration:0.2s;
 transition-timing-function:ease;
}

nav ul li a:hover {
 color:#FFFFFF;
}

nav ul li:hover a::after {
 height:4px;
 background-color:var(--dark-green);
}

nav ul li.active a::after {
 height:4px;
 background-color:#FFFFFF;
}

.view-source-button {
 color:#FFFFFF;
 background-color:var(--dark-green);
}

.view-source-button:hover {
 background-color:var(--light-blue);
}



main {
 height:height;
 padding:0px 10px 60px 10px;
 display:flex;
 flex-direction:row;
 align-items:flex-start;
 justify-content:center;
 box-sizing:border-box;
}

#page-content {
 width:calc(100% - 320px);
 max-width:1200px;
 padding:10px;
 border-radius:5px;
 flex-shrink:1;
 display:flex;
 flex-direction:column;
 align-items:center;
 justify-content:flex-start;
 box-sizing:border-box;
}

aside {
 width:320px;
 height:100%;
 padding:10px;
 flex-shrink:0;
 box-sizing:border-box;
}

#page-content section,
aside section {
 width:100%;
 background-color:#FFFFFF;
 padding:0px;
 border-radius:5px;
 margin:10px 0px;
 box-sizing:border-box;
}

.section-title {
 font-weight:400;
 text-transform:uppercase;
 color:#000000;
 padding:6px 0px;
 display:flex;
 flex-direction:row;
 align-items:center;
 justify-content:center;
 box-sizing:border-box;
}

.section-row {
 width:100%;
 text-decoration:none;
 color:#000000;
 border-top:1px solid var(--light-gray);
 margin:0px;
 cursor:pointer;
 display:flex;
 flex-direction:row;
 align-items:center;
 justify-content:space-between;
 box-sizing:border-box;
}

.section-row:hover {
 color:inherit;
 background-color:var(--white-green);
}

.section-row-content {
 padding:10px 16px;
}

.flexbox {
 display:flex;
 flex-direction:column;
 align-items:center;
 justify-content:flex-start;
}

.grid {
 display:grid;
 grid-gap:10px;
}

.grid section {
 margin:0px !important;
}

.card {
 box-shadow:0px 0px 5px -2px rgb(0, 0, 0, 0.2);
}



.event-title {
 font-weight:800;
}

.section-row:hover .event-title {
 color:var(--dark-green);
}

.event-author {
 font-size:13px;
}

.event-section-end-button {
 width:100%;
 font-weight:400;
 text-transform:uppercase;
 color:var(--dark-green);
 padding:6px 0px;
 border-top:1px solid var(--light-gray);
 cursor:pointer;
 display:flex;
 flex-direction:row;
 align-items:center;
 justify-content:center;
 box-sizing:border-box;
}

.event-section-end-button:hover {
 color:var(--dark-green);
 background-color:var(--white-green);
}



/* blog */

#blog-section {
 margin:0px !important;
}

#blog-shadow {
 width:100%;
 transition-property:box-shadow;
 transition-delay:0.6s;
 transition-duration:0.2s;
 transition-timing-function:ease;
 overflow:hidden;
}

#blog-overview {
 width:100%;
 position:relative;
 box-sizing:border-box;
}

#blog-overview-contain {
 padding:10px 0px !important;
 position:relative;
 display:flex;
 flex-direction:row;
 align-items:flex-start;
 justify-content:flex-start;
}

#blog-overview-slider {
 width:auto;
 position:relative;
 display:flex;
 flex-direction:row;
 align-items:normal;
 justify-content:flex-start;
 box-sizing:border-box;
 transition-property:margin-left;
 transition-duration:0.6s;
 transition-timing-function:ease;
}

.blog-article-box {
 width:320px;
 min-width:320px;
 max-width:calc(100% * 0.6);
 background-color:#FFFFFF;
 border-radius:5px;
 margin:0px;
 cursor:pointer;
 overflow:hidden;
 position:relative;
 display:flex;
 flex-direction:column;
 align-items:center;
 justify-content:flex-start;
 box-sizing:border-box;
}

.blog-article-box:not(:first-child) {
 margin-left:10px;
}

.blog-article-box-header {
 width:100%;
 text-align:center;
 padding:10px 16px;
 display:flex;
 flex-direction:column;
 align-items:center;
 justify-content:center;
 border-bottom:1px solid var(--light-gray);
 box-sizing:border-box;
}

.blog-article-box-title {
 font-weight:800;
 font-family:Jost Semi, Lato, Cantarell, sans-serif;
 text-transform:uppercase;
}

.blog-article-box-author::before {
 content:"by";
 margin:0px 6px 0px 0px;
}

.blog-article-box-date {
 color:var(--gray);
}

.blog-article-box-body {
 width:100%;
 height:100%;
}

.blog-article-box-footer {
 width:100%;
 display:flex;
 flex-direction:row;
 align-items:center;
 justify-content:center;
 border-top:1px solid var(--light-gray);
}



#later-articles-button-gradient,
#earlier-articles-button-gradient {
 top:0px;
 bottom:0px;
}

#later-articles-button,
#earlier-articles-button {
 height:40px;
 color:var(--dark-green);
 background-color:#FFFFFF;
 padding:0px 16px;
 border-radius:5px;
 cursor:pointer;
 box-shadow:0px 0px 5px -2px rgb(0, 0, 0, 0.6);
 flex-shrink:0;
 display:flex;
 flex-direction:row;
 align-items:center;
 justify-content:center;
 transition-duration:0.2s;
 transition-timing-function:ease;
}

#later-articles-button-gradient {
 width:100px;
 height:100%;
 background-image:linear-gradient(to right, var(--light-gray) 0%, transparent 100%);
 position:absolute;
 left:0px;
 overflow:hidden;
 display:flex;
 flex-direction:row;
 align-items:center;
 justify-content:flex-start;
 transition-property:width, opacity;
 transition-duration:0.2s;
 transition-timing-function:ease;
}

#later-articles-button {
 transition-property:margin-left;
}

#earlier-articles-button-gradient {
 width:100px;
 height:100%;
 background-image:linear-gradient(to right, transparent 0%, var(--light-gray) 100%);
 position:absolute;
 right:0px;
 overflow:hidden;
 display:flex;
 flex-direction:row;
 align-items:center;
 justify-content:flex-end;
 transition-property:width, opacity;
 transition-duration:0.2s;
 transition-timing-function:ease;
}

#earlier-articles-button {
 transition-property:margin-right;
}

#later-articles-button:hover,
#earlier-articles-button:hover {
 background-color:var(--light-green);
}



#blog-article-expand-area.inactive {
 height:0px;
 padding:0px 16px;
 margin-top:0px;
 opacity:0;
}

#blog-article-expand-area {
 width:100%;
 background-color:#FFFFFF;
 border-radius:5px;
 margin-top:10px;
 opacity:1;
 box-sizing:border-box;
 transition-property:height, padding, margin-top, opacity;
 transition-delay:0s, 0s, 0s, 0.2s;
 transition-duration:0.2s;
 transition-timing-function:ease;
}

#blog-article-expand-header {
 width:100%;
 padding:10px 16px;
 display:flex;
 flex-direction:row;
 align-items:center;
 justify-content:flex-start;
 border-bottom:1px solid var(--light-gray);
 box-sizing:border-box;
 transition-property:opacity;
 transition-duration:0.2s;
 transition-timing-function:ease;
}

#blog-article-expand-title {
 font-weight:800;
 font-family:Jost Semi, Lato, Cantarell, sans-serif;
 text-transform:uppercase;
}

#blog-article-expand-author {
 margin-left:10px;
}

#blog-article-expand-author::before {
 content:"by";
 margin-right:6px;
}

#blog-article-expand-date {
 color:var(--gray);
 margin-left:10px;
 display:flex;
 flex-direction:center;
}

#blog-article-expand-date::before {
 content:"";
 border-left:1px solid var(--light-gray);
 margin-right:10px;
}

#blog-article-expand-body {
 transition-property:opacity;
 transition-duration:0.2s;
 transition-timing-function:ease;
}

/* blog END */






```
